config/routes.rb
#
# OLIGAA - Stands for "Outil en Ligne d'Information et de Gestion des Activités
# des Associations" which is an online tool for associations to manage news,
# actors and activities.
# Copyright (C) 2010-2019 Comité Départemental du Sport Adapté de la Gironde (CDSA
# 33) <contact@cdsa33.org>
#
# This file is part of OLIGAA.
#
# OLIGAA is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# OLIGAA is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with OLIGAA.  If not, see <http://www.gnu.org/licenses/>.
#
Rails.application.routes.draw do
  resources :events
  resources :event_types do
    patch :update_ga_events, :on => :member
  end
  resources :menus, :except => [:index, :show] do
    member do
      patch :move_up
      patch :move_down
    end
  end
  resources :pages do
    member do
      patch :move_up
      patch :move_down
    end
  end
  resources :activity_categories, :except => :index
  resources :activities
  resources :sessions, :only => [:new, :create, :destroy]
  resource :settings, :only => [:edit, :update]
  resources :novel_types, :except => :index
  resources :novels do
    collection do
      get :public_index
      get :feed
    end
    get :duplicate, :on => :member
  end
  resources :members do
    get :raz_pass, :on => :member
    post :search_contacts, on: :collection
    get :map, on: :collection
    resources :performances, except: [:index, :show] do
      patch :toggle, on: :member
    end
    resources :subscriptions do
      get :option, on: :collection
      get :card, on: :member
      patch :toggle_billing, on: :member
      get :renew, on: :member
    end
  end
  resources :member_groups, :except => [:index] do
    member do
      patch :filter_members
      get :members
    end
  end
  resources :public_types
  resources :emails do
    patch :send_off, :on => :member
    get :recipients_by_member_groups, :on => :member
    get :recipients_by_contact_types, :on => :member
  end
  resources :contact_types, :except => :show
  resource :contact_us, :only => [:new, :create], :path_names => { :new => "write"}
  resources :newsletters
  resources :partners do
    member do
      patch :move_up
      patch :move_down
    end
    get :display, on: :collection
  end
  resources :partners_groups, except: [:index, :show] do
    member do
      patch :move_up
      patch :move_down
    end
  end
  resources :club_novels, except: :show

  patch '/newsletter_items/:id/move_up' => 'newsletter_items#move_up', as: 'move_up_item'
  patch '/newsletter_items/:id/move_down' => 'newsletter_items#move_down', as: 'move_down_item'

  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout

  get '/calendar(/:year(/:month))' => 'calendar#show', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  get '/calendar(/:year(/:month.pdf))' => 'calendar#show', :as => :calendar_pdf, :format => :pdf, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  patch 'filter_calendar' => 'calendar#update', :as => :filter_calendar

  get '/help/redcloth' => 'help#redcloth', :as => :redcloth_help

  get '/sitemap' => 'sitemap#index', :as => :sitemap

  get '/platform' => 'platform#index', as: :platform

  root :to => 'novels#public_index'
end

app/models/newsletter.rb
#
# OLIGAA - Stands for "Outil en Ligne d'Information et de Gestion des Activités
# des Associations" which is an online tool for associations to manage news,
# actors and activities.
# Copyright (C) 2010-2019 Comité Départemental du Sport Adapté de la Gironde (CDSA
# 33) <contact@cdsa33.org>
#
# This file is part of OLIGAA.
#
# OLIGAA is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# OLIGAA is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with OLIGAA.  If not, see <http://www.gnu.org/licenses/>.
#
class Newsletter < ApplicationRecord
  include URLEncoding

  has_many :items, class_name: "NewsletterItem", :dependent => :destroy
  accepts_nested_attributes_for :items, :allow_destroy => true
  has_and_belongs_to_many :partners

  validates :title, presence: true
  validates_associated :items

  scope :published, -> { where(published: true) }
  scope :ordered, -> { order("created_at DESC") }
  scope :for_nav, -> { published.ordered.limit(3) }

  def pdf_filename
    "#{ENV['APP_NAME']} - #{my_url_encode(title.chomp)}.pdf"
  end

  def has_pdf?
    File.exists?(pdf_path)
  end

  def pdf_path
    Rails.root + "public/system/pdfs/newsletters/" + pdf_filename
  end
end

app/controllers/newsletters_controller.rb
#
# OLIGAA - Stands for "Outil en Ligne d'Information et de Gestion des Activités
# des Associations" which is an online tool for associations to manage news,
# actors and activities.
# Copyright (C) 2010-2019 Comité Départemental du Sport Adapté de la Gironde (CDSA
# 33) <contact@cdsa33.org>
#
# This file is part of OLIGAA.
#
# OLIGAA is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# OLIGAA is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with OLIGAA.  If not, see <http://www.gnu.org/licenses/>.
#
class NewslettersController < ApplicationController
  before_action :authorize, except: [:index, :show]

  def index
    @newsletters = admin? ? Newsletter.ordered : Newsletter.ordered.published
    @for_nav = Newsletter.for_nav
  end

  def new
    @newsletter = Newsletter.new({partner_ids: settings.partners.map(&:id)})
    prepare_partners
  end

  def create
    @newsletter = Newsletter.new(newsletter_params)
    if @newsletter.save
      schedule_pdf
      redirect_to @newsletter
    else
      render :new
    end
  end

  def show
    @newsletter = Newsletter.find(params[:id])
    @partners = @newsletter.partners
    if admin? || @newsletter.published?
      respond_to do |format|
        format.html
        format.pdf do
          if @newsletter.has_pdf?
            send_file @newsletter.pdf_path, type: 'application/pdf'
            expires_now
          else
            flash[:alert] = "Le PDF n'a pas encore été généré. Merci de revenir plus tard."
            redirect_to @newsletter
          end
        end
      end
    else
      authorize
    end
  end

  def edit
    @newsletter = Newsletter.find(params[:id])
    prepare_partners
  end

  def update
    @newsletter = Newsletter.find(params[:id])
    if @newsletter.update_attributes(newsletter_params)
      schedule_pdf
      redirect_to @newsletter
    else
      render :edit
    end
  end

  def destroy
    Newsletter.find(params[:id]).destroy
    redirect_to newsletters_path
  end

  private

  def prepare_partners
    @partners = Partner.by_name
  end

  def schedule_pdf
    if @newsletter.published?
      File.delete(@newsletter.pdf_path) if @newsletter.has_pdf?
      Delayed::Job.enqueue(PdfJob.new(newsletter_url(@newsletter), @newsletter.pdf_filename))
      flash[:notice] = "La génération du PDF a été planifiée."
    end
  end

  def newsletter_params
    params.require(:newsletter).permit(:title, :published, partner_ids: [],
      items_attributes: [
        :id, :content, :newsletter_id, :title, :photo, :delete_photo, :_destroy, activity_ids: [],
        images_attributes: image_permitted_attributes,
        attached_files_attributes: attached_file_permitted_attributes
        ])
  end
end

app/helpers/newsletters_helper.rb
#
# OLIGAA - Stands for "Outil en Ligne d'Information et de Gestion des Activités
# des Associations" which is an online tool for associations to manage news,
# actors and activities.
# Copyright (C) 2010-2019 Comité Départemental du Sport Adapté de la Gironde (CDSA
# 33) <contact@cdsa33.org>
#
# This file is part of OLIGAA.
#
# OLIGAA is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# OLIGAA is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with OLIGAA.  If not, see <http://www.gnu.org/licenses/>.
#
module NewslettersHelper
  def partner_link(partner, size = :standard, with_title = true)
    data = ""
    if partner.url.present? && partner.logo?
      # image cliquable + nom normal
      data << "<span>#{partner.name}</span>" if with_title
      data << link_to(image_tag(partner.logo.url(size), alt: partner.name), partner.url, class: "externe")
    elsif partner.url.present? && !partner.logo?
      # nom cliquable
      data << link_to(partner.name, partner.url, class: "externe")
    elsif !partner.url.present? && partner.logo?
      # image normale + nom normal
      data << "<span>#{partner.name}</span>"
      data << image_tag(partner.logo.url(size), alt: partner.name)
    else
      # nom normal
      data << "<span>#{partner.name}</span>"
    end
    data.html_safe
  end
end

app/views/newsletters/_form.html.erb
<%
# OLIGAA - Stands for "Outil en Ligne d'Information et de Gestion des Activités
# des Associations" which is an online tool for associations to manage news,
# actors and activities.
# Copyright (C) 2010-2019 Comité Départemental du Sport Adapté de la Gironde (CDSA
# 33) <contact@cdsa33.org>
#
# This file is part of OLIGAA.
#
# OLIGAA is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# OLIGAA is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with OLIGAA.  If not, see <http://www.gnu.org/licenses/>.
%>
<p><%= redcloth_help %></p>

<%= simple_nested_form_for @newsletter do |f| %>

	<div class="tabs">
		<ul>
			<li><a href="#general">Général</a></li>
			<li><a href="#items">Informations</a></li>
			<li><a href="#partners">Partenaires</a></li>
		</ul>
		<div id="general">
			<%= f.input :title %>
			<%= f.input :published %>		
		</div>
		<div id="items">
			<%= f.fields_for :items %>
			<p><%= f.link_to_add "Ajouter un item", :items %></p>		
		</div>
		<div id="partners">
			<%= f.association :partners, collection: @partners, as: :check_boxes %>
		</div>
	</div>

	<p><%= f.button :submit %></p>
<% end %>

app/views/newsletters/_item_fields.html.erb
<%
# OLIGAA - Stands for "Outil en Ligne d'Information et de Gestion des Activités
# des Associations" which is an online tool for associations to manage news,
# actors and activities.
# Copyright (C) 2010-2019 Comité Départemental du Sport Adapté de la Gironde (CDSA
# 33) <contact@cdsa33.org>
#
# This file is part of OLIGAA.
#
# OLIGAA is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# OLIGAA is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with OLIGAA.  If not, see <http://www.gnu.org/licenses/>.
%>
<% item = f.object %>
<% id = item.id %>
<div class="edit_newsletter_item">
	<p><%= f.link_to_remove "Supprimer l'item" %></p>
	<div class="tabs">
		<ul>
			<li><a href="#general-<%= id %>">Général</a></li>
			<li><a href="#activities-<%= id %>">Activités</a></li>
			<li><a href="#attachments-<%= id %>">Pièces jointes</a></li>
			<li><a href="#images-<%= id %>">Images</a></li>
		</ul>
		<div id="general-<%= id %>">
			<%= f.input :title, input_html: {class: "small_text"} %>
			<%= f.input :content %>
		</div>
		<div id="activities-<%= id %>">
			<%= f.association :activities, as: :check_boxes %>
		</div>
		<div id="attachments-<%= id %>">
			<%= render 'attached_files_form', :f => f %>
		</div>
		<div id="images-<%= id %>">
			<%= render 'images_form', :f => f %>
		</div>
	</div>
</div>

app/views/newsletters/edit.html.erb
<%
# OLIGAA - Stands for "Outil en Ligne d'Information et de Gestion des Activités
# des Associations" which is an online tool for associations to manage news,
# actors and activities.
# Copyright (C) 2010-2019 Comité Départemental du Sport Adapté de la Gironde (CDSA
# 33) <contact@cdsa33.org>
#
# This file is part of OLIGAA.
#
# OLIGAA is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# OLIGAA is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with OLIGAA.  If not, see <http://www.gnu.org/licenses/>.
%>
<% title 'Edition de la newsletter' %>
<div class="card-block">
	<h1><%= yield :title %></h1>

	<p class="AdminCard-globalActions">
    <%= custom_show_link @newsletter, 'Afficher' %>
    <%= custom_list_link newsletters_path %>
  </p>

  <%= render 'form' %>
</div>

app/views/newsletters/index.html.erb
<%
# OLIGAA - Stands for "Outil en Ligne d'Information et de Gestion des Activités
# des Associations" which is an online tool for associations to manage news,
# actors and activities.
# Copyright (C) 2010-2019 Comité Départemental du Sport Adapté de la Gironde (CDSA
# 33) <contact@cdsa33.org>
#
# This file is part of OLIGAA.
#
# OLIGAA is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# OLIGAA is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with OLIGAA.  If not, see <http://www.gnu.org/licenses/>.
%>
<% title 'Liste des newsletters' %>
<% breadcrumb :newsletter_archives %>

<div class="card-block">
	<h1><%= yield :title %></h1>

	<% if admin? %>
	<p class="AdminCard-globalActions">
		<%= custom_add_link 'Nouvelle newsletter', new_newsletter_path %>
	</p>
	<% end -%>

	<ul id="newsletters_listing">
		<% @newsletters.each do |newsletter| %>
		<li>
			<h2>
				<% if admin? %>
				<span class="no_print">
					<%= custom_delete_link newsletter, :short, class: %w(tight) %>
					<%= custom_edit_link edit_newsletter_path(newsletter), :short, class: %w(tight) %>
				</span>
				<% end -%>
				<%= link_to newsletter.title, newsletter, class: @for_nav.include?(newsletter) ? '' : 'js-append-trail' %>
			</h2>
			<ul>
				<% newsletter.items.each do |item| %>
				<li><%= raw textilize_without_paragraph item.title %></li>
				<% end -%>
			</ul>
		<% end %>
		</li>
	</ul>
</div>

app/views/newsletters/new.html.erb
<%
# OLIGAA - Stands for "Outil en Ligne d'Information et de Gestion des Activités
# des Associations" which is an online tool for associations to manage news,
# actors and activities.
# Copyright (C) 2010-2019 Comité Départemental du Sport Adapté de la Gironde (CDSA
# 33) <contact@cdsa33.org>
#
# This file is part of OLIGAA.
#
# OLIGAA is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# OLIGAA is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with OLIGAA.  If not, see <http://www.gnu.org/licenses/>.
%>
<% title 'Nouvelle newsletter' %>
<div class="card-block">
	<h1><%= yield :title %></h1>

	<p class="AdminCard-globalActions">
    <%= custom_list_link newsletters_path %>
  </p>

  <%= render 'form' %>
</div>

app/views/newsletters/show.html.erb
<%
# OLIGAA - Stands for "Outil en Ligne d'Information et de Gestion des Activités
# des Associations" which is an online tool for associations to manage news,
# actors and activities.
# Copyright (C) 2010-2019 Comité Départemental du Sport Adapté de la Gironde (CDSA
# 33) <contact@cdsa33.org>
#
# This file is part of OLIGAA.
#
# OLIGAA is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# OLIGAA is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with OLIGAA.  If not, see <http://www.gnu.org/licenses/>.
%>
<% title @newsletter.title %>
<% breadcrumb @newsletter %>

<div id="newsletter">
	<hgroup>
		<h1><%= settings.newsletters_title %> - <%= yield :title %></h1>
    <% if admin? %>
    <p class="AdminCard-globalActions">
      <%= custom_edit_link edit_newsletter_path(@newsletter) %>
    </p>
    <% end %>
	</hgroup>

	<span id="reference"><%= newsletter_url(@newsletter) %></span>


	<ul id="newsletter_items">
	<% @newsletter.items.ordered.each do |item| %>
		<li class="newsletter_item">
			<div class="item_desc">
				<h2>
          <% if admin? %>
          <span class="no_print">
            <%= custom_move_up_link move_up_item_path(item), :short, class: %w(tight) unless item.first? %>
            <%= custom_move_down_link move_down_item_path(item), :short, class: %w(tight) unless item.last? %>
          </span>
          <% end -%>
          <%= raw textilize_without_paragraph item.title %>
        </h2>

				<%= textilize raw item.content %>

				<% unless item.attached_files.empty? %>
				<h3>Pièces jointes</h3>
					<dl class="attachments">
						<%= render partial: 'attachment', collection: item.attached_files %>
					</dl>
				<% end -%>
			</div>
			<div class="item_aside">
				<ul class="activities">
				<% item.activities.each do |activity| %>
					<li>
						<% if activity.poster? %>
							<%= image_tag activity.poster.url(:standard), title: activity.title %>
						<% else %>
							<%= activity.title %>
						<% end %>
					</li>
				<% end %>
				</ul>
				<ul class="gallery">
					<% item.images.each do |img| %>
					<li>
						<%= link_to image_tag(img.img_file.url(:thumb), alt: img.title, class: "photo"), img.img_file.url(:large), rel: "prettyPhoto[gallery-#{item.id.to_s}]" %>
					</li>
					<% end %>
				</ul>
				<% unless item.images.empty? %>
				<span class="images-number"><%= item.images.length %> image(s)</span>
				<% end %>
			</div>
		</li>
	<% end %>
	</ul>

	<div id="partners">
		<ul class="partners">
		<% @partners.each do |partner| %>
			<li class="<%= cycle "", "", "omega" %>"><%= partner_link partner, :thumb, false %>
			</li>
		<% end %>
		</ul>

		<% if @newsletter.has_pdf? %>
		<div class="print_to_pdf"><%= link_to "Version imprimable", newsletter_path(@newsletter, format: :pdf), rel: "nofollow" %></span>
		<% end %>
	</div>

</div>