config/routes.rb
#
# OLIGAA - Stands for "Outil en Ligne d'Information et de Gestion des Activités
# des Associations" which is an online tool for associations to manage news,
# actors and activities.
# Copyright (C) 2010-2019 Comité Départemental du Sport Adapté de la Gironde (CDSA
# 33) <contact@cdsa33.org>
#
# This file is part of OLIGAA.
#
# OLIGAA is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# OLIGAA is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with OLIGAA.  If not, see <http://www.gnu.org/licenses/>.
#
Rails.application.routes.draw do
  resources :events
  resources :event_types do
    patch :update_ga_events, :on => :member
  end
  resources :menus, :except => [:index, :show] do
    member do
      patch :move_up
      patch :move_down
    end
  end
  resources :pages do
    member do
      patch :move_up
      patch :move_down
    end
  end
  resources :activity_categories, :except => :index
  resources :activities
  resources :sessions, :only => [:new, :create, :destroy]
  resource :settings, :only => [:edit, :update]
  resources :novel_types, :except => :index
  resources :novels do
    collection do
      get :public_index
      get :feed
    end
    get :duplicate, :on => :member
  end
  resources :members do
    get :raz_pass, :on => :member
    post :search_contacts, on: :collection
    get :map, on: :collection
    resources :performances, except: [:index, :show] do
      patch :toggle, on: :member
    end
    resources :subscriptions do
      get :option, on: :collection
      get :card, on: :member
      patch :toggle_billing, on: :member
      get :renew, on: :member
    end
  end
  resources :member_groups, :except => [:index] do
    member do
      patch :filter_members
      get :members
    end
  end
  resources :public_types
  resources :emails do
    patch :send_off, :on => :member
    get :recipients_by_member_groups, :on => :member
    get :recipients_by_contact_types, :on => :member
  end
  resources :contact_types, :except => :show
  resource :contact_us, :only => [:new, :create], :path_names => { :new => "write"}
  resources :newsletters
  resources :partners do
    member do
      patch :move_up
      patch :move_down
    end
    get :display, on: :collection
  end
  resources :partners_groups, except: [:index, :show] do
    member do
      patch :move_up
      patch :move_down
    end
  end
  resources :club_novels, except: :show

  patch '/newsletter_items/:id/move_up' => 'newsletter_items#move_up', as: 'move_up_item'
  patch '/newsletter_items/:id/move_down' => 'newsletter_items#move_down', as: 'move_down_item'

  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout

  get '/calendar(/:year(/:month))' => 'calendar#show', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  get '/calendar(/:year(/:month.pdf))' => 'calendar#show', :as => :calendar_pdf, :format => :pdf, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  patch 'filter_calendar' => 'calendar#update', :as => :filter_calendar

  get '/help/redcloth' => 'help#redcloth', :as => :redcloth_help

  get '/sitemap' => 'sitemap#index', :as => :sitemap

  get '/platform' => 'platform#index', as: :platform

  root :to => 'novels#public_index'
end

app/models/activity.rb
#
# OLIGAA - Stands for "Outil en Ligne d'Information et de Gestion des Activités
# des Associations" which is an online tool for associations to manage news,
# actors and activities.
# Copyright (C) 2010-2019 Comité Départemental du Sport Adapté de la Gironde (CDSA
# 33) <contact@cdsa33.org>
#
# This file is part of OLIGAA.
#
# OLIGAA is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# OLIGAA is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with OLIGAA.  If not, see <http://www.gnu.org/licenses/>.
#
class Activity < ApplicationRecord
  include SeasonedEventsConcern

  has_and_belongs_to_many :activity_categories, :join_table => :activities_cats
  has_and_belongs_to_many :events
  has_and_belongs_to_many :members
  has_and_belongs_to_many :novels
  has_many :attached_files, :as => :attachable, :dependent => :destroy
  accepts_nested_attributes_for :attached_files, :allow_destroy => true
  has_attached_file :poster, :styles => { :thumb => "20x20", :standard => "120x120" }, :convert_options => { :all => '-strip -colorspace RGB'}
  validates_attachment_size :poster, :less_than => 1.megabyte, :message => "doit faire moins de 1 MB", :if => Proc.new { |file| !file.poster_file_name.blank? }
  do_not_validate_attachment_file_type :poster
  has_many :performances, dependent: :destroy

  default_scope { order('title ASC') }
  scope :filterable, -> { where(filterable: true) }
  scope :listed, -> { where(listed: true) }

  validates_presence_of :title
  validates_presence_of :presentation

  def self.uncategorized
    all.reject { |act| !act.activity_categories.blank? }
  end
end

app/controllers/activities_controller.rb
#
# OLIGAA - Stands for "Outil en Ligne d'Information et de Gestion des Activités
# des Associations" which is an online tool for associations to manage news,
# actors and activities.
# Copyright (C) 2010-2019 Comité Départemental du Sport Adapté de la Gironde (CDSA
# 33) <contact@cdsa33.org>
#
# This file is part of OLIGAA.
#
# OLIGAA is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# OLIGAA is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with OLIGAA.  If not, see <http://www.gnu.org/licenses/>.
#
class ActivitiesController < ApplicationController
  before_action :authorize, :except => [ :show ]

  def index
    @activity_categories = ActivityCategory.all
    @uncategorized_activities = Activity.uncategorized
  end

  def show
    @activity = Activity.find(params[:id])
    @seasoned_events = @activity.seasoned_events
    @available_member_groups = settings.map_member_groups & MemberGroup.for_activity(@activity)
  end

  def new
    @activity = Activity.new
  end

  def edit
    @activity = Activity.find(params[:id])
  end

  def create
    @activity = Activity.new(activity_params)
    if @activity.save
      flash[:notice] = 'Activité créée avec succès.'
      redirect_to @activity
    else
      flash[:error] = t('flash.error')
      render :action => "new"
    end
  end

  def update
    @activity = Activity.find(params[:id])
    if params[:activity][:_destroy] == "1"
      @activity.poster.destroy
    end
    if @activity.update_attributes(activity_params)
      flash[:notice] = 'Activité mise à jour avec succès.'
      redirect_to @activity
    else
      flash[:error] = t('flash.error')
      render :action => "edit"
    end
  end

  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy
    flash[:notice] = 'Activité supprimée avec succès.'
    redirect_to activities_url
  end

  private

  def activity_params
    params.require(:activity).permit(:title, :presentation, :description, :poster, :filterable, :listed, attached_files_attributes: attached_file_permitted_attributes, activity_category_ids: [])
  end
end

app/views/activities/_activity.html.erb
<%
# OLIGAA - Stands for "Outil en Ligne d'Information et de Gestion des Activités
# des Associations" which is an online tool for associations to manage news,
# actors and activities.
# Copyright (C) 2010-2019 Comité Départemental du Sport Adapté de la Gironde (CDSA
# 33) <contact@cdsa33.org>
#
# This file is part of OLIGAA.
#
# OLIGAA is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# OLIGAA is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with OLIGAA.  If not, see <http://www.gnu.org/licenses/>.
%>
<li>
  <span class="no_print">
    <%= custom_delete_link activity, :short, class: %w(tight) %>
    <%= custom_edit_link edit_activity_path(activity), :short, class: %w(tight) %>
    <%= custom_show_link activity, activity.title, :normal, class: %w(tight) %>
  </span>
</li>

app/views/activities/_form.html.erb
<%
# OLIGAA - Stands for "Outil en Ligne d'Information et de Gestion des Activités
# des Associations" which is an online tool for associations to manage news,
# actors and activities.
# Copyright (C) 2010-2019 Comité Départemental du Sport Adapté de la Gironde (CDSA
# 33) <contact@cdsa33.org>
#
# This file is part of OLIGAA.
#
# OLIGAA is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# OLIGAA is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with OLIGAA.  If not, see <http://www.gnu.org/licenses/>.
%>
<p><%= redcloth_help %></p>

<%= simple_nested_form_for @activity, html: { multipart: true } do |f| %>
	<div class="tabs">
		<ul>
			<li><a href="#general">Général</a></li>
			<li><a href="#attachments">Pièces jointes (<%= @activity.attached_files.count %>)</a></li>
		</ul>
		<div id="general">
			<%= f.input :title %>
			<%= f.input :presentation %>
			<%= f.input :description %>
			<%= f.association :activity_categories, as: :check_boxes %>
			<% if @activity.poster.file? %>
				<%= image_tag @activity.poster.url(:standard) %>
				<%= f.label :_destroy, "Supprimer l'image" %>
				<%= f.check_box :_destroy %>
			<% else %>
				<%= f.input :poster %>			
			<% end %>
			<%= f.input :listed %>
			<%= f.input :filterable %>
		</div>
		<div id="attachments">
			<%= render 'attached_files_form', :f => f %>
		</div>
	</div>
  <p>
    <%= f.button :submit %>
  </p>
<% end %>

app/views/activities/edit.html.erb
<%
# OLIGAA - Stands for "Outil en Ligne d'Information et de Gestion des Activités
# des Associations" which is an online tool for associations to manage news,
# actors and activities.
# Copyright (C) 2010-2019 Comité Départemental du Sport Adapté de la Gironde (CDSA
# 33) <contact@cdsa33.org>
#
# This file is part of OLIGAA.
#
# OLIGAA is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# OLIGAA is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with OLIGAA.  If not, see <http://www.gnu.org/licenses/>.
%>
<% title "Edition d'une activité" %>

<div class="card-block">
  <h1><%= yield :title %></h1>

  <p class="AdminCard-globalActions">
    <%= custom_show_link @activity, 'Afficher' %>
    <%= custom_list_link activities_path %>
  </p>

  <%= render :partial => 'form' %>
</div>

app/views/activities/index.html.erb
<%
# OLIGAA - Stands for "Outil en Ligne d'Information et de Gestion des Activités
# des Associations" which is an online tool for associations to manage news,
# actors and activities.
# Copyright (C) 2010-2019 Comité Départemental du Sport Adapté de la Gironde (CDSA
# 33) <contact@cdsa33.org>
#
# This file is part of OLIGAA.
#
# OLIGAA is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# OLIGAA is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with OLIGAA.  If not, see <http://www.gnu.org/licenses/>.
%>
<% title 'Liste des activités' %>

<div class="card-block">
  <h1><%= yield :title %></h1>

  <p class="AdminCard-globalActions">
  	<%= custom_add_link "Nouvelle catégorie d'activité", new_activity_category_path %>
  	<%= custom_add_link 'Nouvelle activité', new_activity_path %>
  </p>

  <ol id="activity_list" class="AdminCard-list">
  	<% @activity_categories.each do |cat| %>
  	<li>
      <h2>
        <%= toggle_link cat.title, "#cat-#{cat.id}" %>
        (<%= cat.activities.count %>)
      </h2>
      <div id="cat-<%= cat.id %>" style="display:none;">
        <p class="AdminCard-headingActions no_print">
          <%= custom_delete_link cat, :short, class: %w(tight) %>
          <%= custom_edit_link edit_activity_category_path(cat), :short, class: %w(tight) %>
          <%= custom_primary_show_link cat, :short, class: %w(tight) %>
        </p>
        <ol>
    			<%= render :partial => 'activity', :collection => cat.activities %>
    		</ol>
      </div>
  	</li>
  	<% end %>
  	<% unless @uncategorized_activities.empty? %>
  	<li>
  		<h2><%= toggle_link "Sans type de catégorie", '#uncat' %>(<%= @uncategorized_activities.count %>)</h2>
  		<ul id="uncat" style="display:none;">
  			<%= render :partial => 'activity', :collection => @uncategorized_activities %>
  		</ul>
  	</li>
  	<% end %>
  </ol>
</div>

app/views/activities/new.html.erb
<%
# OLIGAA - Stands for "Outil en Ligne d'Information et de Gestion des Activités
# des Associations" which is an online tool for associations to manage news,
# actors and activities.
# Copyright (C) 2010-2019 Comité Départemental du Sport Adapté de la Gironde (CDSA
# 33) <contact@cdsa33.org>
#
# This file is part of OLIGAA.
#
# OLIGAA is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# OLIGAA is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with OLIGAA.  If not, see <http://www.gnu.org/licenses/>.
%>
<% title "Nouvelle activité" %>

<div class="card-block">
  <h1><%= yield :title %></h1>

  <p class="AdminCard-globalActions">
    <%= custom_list_link activities_path %>
  </p>

  <%= render :partial => 'form' %>
</div>

app/views/activities/show.html.erb
<%
# OLIGAA - Stands for "Outil en Ligne d'Information et de Gestion des Activités
# des Associations" which is an online tool for associations to manage news,
# actors and activities.
# Copyright (C) 2010-2019 Comité Départemental du Sport Adapté de la Gironde (CDSA
# 33) <contact@cdsa33.org>
#
# This file is part of OLIGAA.
#
# OLIGAA is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# OLIGAA is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with OLIGAA.  If not, see <http://www.gnu.org/licenses/>.
%>
<% title @activity.title %>
<% breadcrumb @activity %>

<article class="card-block">
	<h1><%= yield :title %></h1>

	<% if admin? %>
	<p class="AdminCard-globalActions">
		<%= custom_edit_link edit_activity_path(@activity), :short %>
		<%= custom_list_link activities_path %>
	</p>
	<% end %>

	<%= image_tag @activity.poster.url(:standard), :class => "poster_right" if @activity.poster.file? %>

	<%= textilize raw @activity.presentation %>

	<%= textilize raw @activity.description %>

	<%= render 'attachments', data: @activity.attached_files %>

	<% unless @seasoned_events.blank? %>
		<h2>Evénements associés</h2>
		<ul>
			<% @seasoned_events.each do |season, events| %>
				<% season_label = season.downcase.gsub(/\s/, '_') %>
					<li>
						<%= toggle_link season, "##{season_label}" %>
						<ul id="<%= season_label %>" style="display:none;">
							<% events.each do |event| %>
							<li>
								<%= link_to event.title, event_path(event) %>
								(<%= l event.begin_at.to_date unless event.begin_at.blank? %>)
							</li>
							<% end %>
						</ul>
					</li>
			<% end %>
		</ul>
	<% end %>
	<% unless @available_member_groups.empty? %>
	<div id="where2practice">
		<h2>Où pratiquer :</h2>
		<ul>
		<% @available_member_groups.each do |mg| %>
			<li><%= link_to mg.title, filter_members_member_group_path(mg, activities: [@activity.id]), method: :patch  %></li>
		<% end %>
		</ul>
	</div>
	<% end %>
</article>